_commit: ec770f0
_src_path: gh:bswck/skeleton
author_username: bswck
docs: true
docs_slug: poetry-pipx
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
org_full_name: Bartosz Sławecki
package_name: poetry_pipx
project_description: A Poetry plugin that allows pipx to take precedence when installing
    CLI dependencies.
publish_on_pypi: true
pypi_project_description: A Poetry plugin that allows pipx to take precedence when
    installing CLI dependencies.
pypi_project_name: poetry-pipx
python_version: '3.8'
repo_name: poetry-pipx
test_suite: true
use_precommit: true
visibility: public
